PW3/Models/ErrorViewModel.cs
namespace PW3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PW3/Models/LoginModel.cs
namespace PW3.Models
{
    public class LoginModel
    {

        public string Login { get; set; }
        public string Senha { get; set; }
    }
}

PW3/Controllers/CursosController.cs
using Microsoft.AspNetCore.Mvc;

namespace PW3.Controllers
{
    public class CursosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PW3/Controllers/DiaSemanaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PW3.Controllers
{
    public class DiaSemanaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PW3/Controllers/DisciplinasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using MySqlX.XDevAPI;
using PW3.Entidades;

namespace PW3.Controllers
{
    public class DisciplinasController : Controller
    {
        private readonly string connectionString = "Server=localhost;Database=aulabd2;Uid=root;Pwd=;";
        // GET: DisciplinasController
        public ActionResult Index()
        {
            List<DisciplinaEntidade> model = new List<DisciplinaEntidade>();

            DisciplinaEntidade item1 = new DisciplinaEntidade();
            item1.Id = 1;
            item1.Nome = "Programação Web";
            item1.Ativo = true;
            model.Add(item1);

            DisciplinaEntidade item2 = new DisciplinaEntidade();
            item1.Id = 2;
            item1.Nome = "Educação Física";
            item1.Ativo = true;
            model.Add(item2);

            return View(model);
        }

        // GET: DisciplinasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DisciplinasController/Create
        public ActionResult Create()
        {
            try
            {
                using (var connection = new MySqlConnection(connectionString))
                {
                    connection.Open();
                    var comando = new MySqlCommand("Insert into Disciplinas (Nome) values (?)", connection);

                    comando.Parameters.AddWithValue("?", dados.Nome);
                    comando.ExecuteNonQuery();

                    connection.Close();

                }

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex) {
            return View();
        }

        // POST: DisciplinasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DisciplinaEntidade dados)
        {
                try
                {
                    using (var connection = new MySqlConnection(connectionString))
                    {
                        connection.Open();
                        var comando = new MySqlCommand("Insert into Disciplinas (Nome) values (?)", connection);

                        comando.Parameters.AddWithValue("?", dados.Nome);
                        comando.ExecuteNonQuery();

                        connection.Close();

                    }

                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    {
                return View();
            }
        }

        // GET: DisciplinasController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DisciplinasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DisciplinasController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DisciplinasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PW3/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PW3.Models;

namespace PW3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //Para criar uma nova tela crie um novo metodo abaixo
        public IActionResult Tiago()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PW3/Controllers/HorariosController.cs
using Microsoft.AspNetCore.Mvc;

namespace PW3.Controllers
{
    public class HorariosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PW3/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using PW3.Models;

namespace PW3.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Logar(LoginModel dados)
        {
            LoginModel model = new LoginModel();
            model.Login = "carlosalberto@gmail.com";
            model.Senha = "gostavatantodevc";
            return View(model);
        }
    }
}

PW3/Controllers/MapaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PW3.Controllers
{
    public class MapaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PW3/Controllers/ProfessoresController.cs
using Microsoft.AspNetCore.Mvc;

namespace PW3.Controllers
{
    public class ProfessoresController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PW3/Controllers/SalasController.cs
using Microsoft.AspNetCore.Mvc;

namespace PW3.Controllers
{
    public class SalasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PW3/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using PW3.Entidades;
using System.Collections.Generic;
using System.Reflection.Metadata.Ecma335;

namespace PW3.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly string connectionString = "Server=localhost;Database=aulabd2;Uid=root;Pwd=;";
        public IActionResult Index()
        {

            List<UsuarioEntidade> model = new List<UsuarioEntidade>();

            using var connection = new MySqlConnection(connectionString);
            connection.Open();

            var cmd = new MySqlCommand("SELECT id, email FROM usuarios", connection);
            using var reader = cmd.ExecuteReader();

            while (reader.Read())
            {
                UsuarioEntidade u = new UsuarioEntidade();
                u.Id = reader.GetInt32("id");
                u.Email = reader.GetString("email");
                model.Add(u);
            }
            connection.Close();
            return View(model);
        }

        public IActionResult Create() { 
         return View();
    }
    }
}

PW3/Views/Cursos/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> Index Cursos </h1>

PW3/Views/DiaSemana/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> Index do Dia da Semana </h1>

PW3/Views/Disciplinas/Create.cshtml
@model PW3.Entidades.DisciplinaEntidade

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>DisciplinaEntidade</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PW3/Views/Disciplinas/Delete.cshtml
@model PW3.Entidades.DisciplinaEntidade

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DisciplinaEntidade</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PW3/Views/Disciplinas/Details.cshtml
@model PW3.Entidades.DisciplinaEntidade

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>DisciplinaEntidade</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

PW3/Views/Disciplinas/Edit.cshtml
@model PW3.Entidades.DisciplinaEntidade

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>DisciplinaEntidade</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PW3/Views/Disciplinas/Index.cshtml
@model IEnumerable<PW3.Entidades.DisciplinaEntidade>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

PW3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PW3/Views/Home/Tiago.cshtml
<form action="" method="">
	<label>Nome</label>
	<input 
		type="type"
		name="name"
		value="" />
		<button>
			Enviar Dados
		</button>
</form>

PW3/Views/Horarios/Index.cshtml
<h1> Index dos Horários </h1>

PW3/Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> Index do Login </h1>

PW3/Views/Login/Logar.cshtml
@model LoginModel
<form action="" method="get">
	<label>Email</label>
	<input type="email"
		   name="Login"
		   value="" />
	<label>Senha</label>
	<input type="password"
		   name="Senha"
		   value="" />
	<button type ="submit" class="btn btn-primary">
		Logar
	</button>
</form>
<h1>@Model.Login</h1>

<h1>@Model.Senha</h1>

PW3/Views/Professores/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> Index dos Professores </h1>

PW3/Views/Salas/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> Index das Salas </h1>

PW3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PW3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PW3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PW3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Login/Logar">
                                Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Home/Fernando">
                                Tela adicionada
                                </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                                    asp-area="" 
                                    asp-controller="Cursos"
                                    asp-action="Index">
                                    Cursos
                                </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                    href="/Professores/Index">
                                Professores
                            </a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" 
                                    href="/Disciplinas/Index">
                                Disciplinas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                    href="/Salas/Index">
                                Salas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               href="/DiaSemana/Index">
                                Dias da Semana
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               href="/Horarios/Index">
                                Horarios
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               href="/Usuarios/Index">
                                Usuarios
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PW3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PW3/Views/Usuarios/Create.cshtml
@@ -0,0 +1,53 @@
@model PW3.Entidades.UsuarioEntidade

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4 offset-4">
        <div class="card">
            <div class="card-header">
                Cadastro de usuário
            </div>
            <div class="card-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Senha" class="control-label"></label>
                        <input asp-for="Senha" class="form-control" />
                        <span asp-validation-for="Senha" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Salvar" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista de usuários</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PW3/Views/Usuarios/Index.cshtml
@model List<PW3.Entidades.UsuarioEntidade>

<h1> Lista de Usuários</h1>

<div class="row">
    <div class="col-2">
        <a href="/Usuarios/Create" class="btn btn-success" >Cadastrar</a>
    </div>
    <div class="col-8">
        <form action="/Usuarios/Index" method="get" >
            <div class="input-group mb-3">
                <input name="query" type="text" class="form-control">
                <button class="btn btn-primary" type="submit">
                    Pesquisar
                </button>
            </div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Email</th>
            <th scope="col"> </th>
           
        </tr>
    </thead>
    <tbody>
        @foreach(var usuario in Model)
        {
            <tr>
                <th>@usuario.Id</th>
                <td>@usuario.Email</td>
                <td></td>
            </tr>
        }
    </tbody>
</table>


            <button id="botao" onclick="Piscar()" >
                Clique aqui  o para piscar
            </button>
            <script>
                function Piscar()
                {
                    var botao = document.getElementById("botao")
                    if(botao.style.backgroundColor == 'red')
                    {
                        botao.style.backgroundColor = 'blue'
                    }else{
                        botao.style.backgroundColor = 'red'
                    }
                }
            </script>